import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from "@/components/ui/toaster"
import {Navbar} from "./components/Navbar";
const inter = Inter({ subsets: ["latin"] });
import GlobelProvider from './GlobelProvider'
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang='en'>

      <body className="mx-5 md:mx-10 ">
<GlobelProvider>
      <Navbar/>
        {children}
        <Toaster />
</GlobelProvider>
        </body>
    </html>
   </ClerkProvider> 
  );
}
